global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "vllm"
    static_configs:
      - targets: ["vllm:8000"]
    metrics_path: /metrics

  - job_name: "triton"
    static_configs:
      - targets: ["triton:8002"]
    metrics_path: /metrics

  - job_name: "triton-trt"
    static_configs:
      - targets: ["triton-trt:8002"]
    metrics_path: /metrics
